// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ApiKey []byte
	UserID int64
	Expiry time.Time
	Scope  string
}

type Permission struct {
	ID   int64
	Code string
}

type Tenant struct {
	ID           int64
	Name         string
	ContactEmail string
	Description  sql.NullString
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TradeLead struct {
	ID          int64
	TenantID    int64
	Title       string
	Description sql.NullString
	Status      string
	Value       string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           int64
	TenantID     int64
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UsersPermission struct {
	UserID       int64
	PermissionID int64
}
