// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Tenant struct {
	ID           int64
	Name         string
	ContactEmail string
	Description  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
