# ===============================================
# LeadHub Service - Docker Compose Development
# ===============================================
# Complete development environment with all dependencies

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: leadhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: leadhub
      POSTGRES_USER: leadhub
      POSTGRES_PASSWORD: leadhub_dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/sql/docker-init:/docker-entrypoint-initdb.d
    networks:
      - leadhub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leadhub -d leadhub"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LeadHub API Service
  leadhub-api:
    build:
      context: .
      dockerfile: Dockerfile
      # Remove target to use final production stage
    container_name: leadhub-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - cmd/api/.env.docker
    ports:
      - "4000:4000"
    volumes:
      # Mount source code for development (hot reload)
      - .:/app
      - /app/bin  # Exclude binary directory
    networks:
      - leadhub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



  # Adminer for database management
  adminer:
    image: adminer:4-standalone
    container_name: leadhub-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - leadhub-network
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha

  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: leadhub-nginx
    restart: unless-stopped
    depends_on:
      - leadhub-api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/nginx.conf:ro
    networks:
      - leadhub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local

# Custom network for service communication
networks:
  leadhub-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
