# =============================================================================
# LeadHub Service - Docker Compose for Development
# =============================================================================
# This setup provides a complete development environment with:
# - PostgreSQL database with proper initialization
# - LeadHub API service with hot reloading
# - MailTrap SMTP simulation
# - Volume mounts for development

version: '3.8'

services:
  # =============================================================================
  # PostgreSQL Database Service
  # =============================================================================
  db:
    image: postgres:16-alpine
    container_name: leadhub-db-dev
    environment:
      POSTGRES_DB: leadhub
      POSTGRES_USER: leadhub
      POSTGRES_PASSWORD: leadhub_dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - leadhub_postgres_data:/var/lib/postgresql/data
      - ./internal/sql/docker-init:/docker-entrypoint-initdb.d
    networks:
      - leadhub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leadhub -d leadhub"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # =============================================================================
  # LeadHub API Service (Development Mode)
  # =============================================================================
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: leadhub-api-dev
    environment:
      # Database Configuration
      LEADHUB_DB_DSN: "postgres://leadhub:leadhub_dev_password@db:5432/leadhub?sslmode=disable"
      
      # Application Configuration
      PORT: 4000
      ENV: development
      
      # SMTP Configuration (MailTrap for development)
      LEADHUB_SMTP_HOST: sandbox.smtp.mailtrap.io
      LEADHUB_SMTP_USERNAME: ${MAILTRAP_USERNAME:-your_username}
      LEADHUB_SMTP_PASSWORD: ${MAILTRAP_PASSWORD:-your_password}
      LEADHUB_SMTP_SENDER: "LeadHub Dev <no-reply@leadhub-dev.local>"
      
      # Rate Limiting (Relaxed for development)
      RATE_LIMIT_RPS: 10
      RATE_LIMIT_BURST: 20
      
      # Database Pool Settings
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 25
      DB_MAX_IDLE_TIME: 15m
    ports:
      - "4000:4000"
    volumes:
      # Mount source code for hot reloading in development
      - .:/app
      - /app/tmp # Exclude tmp directory
    depends_on:
      db:
        condition: service_healthy
    networks:
      - leadhub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # =============================================================================
  # Database Migration Service (Runs once)
  # =============================================================================
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: leadhub-migrate-dev
    environment:
      LEADHUB_DB_DSN: "postgres://leadhub:leadhub_dev_password@db:5432/leadhub?sslmode=disable"
    command: ["./migrate-up.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - leadhub-network
    volumes:
      - ./internal/sql/schema:/app/migrations

# =============================================================================
# Networks and Volumes
# =============================================================================
networks:
  leadhub-network:
    driver: bridge
    name: leadhub-dev-network

volumes:
  leadhub_postgres_data:
    name: leadhub-postgres-dev-data
