# ===============================================
# LeadHub Service - Complete Testing Environment
# ===============================================
# This setup demonstrates the full production stack

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: leadhub-test-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: leadhub
      POSTGRES_USER: leadhub
      POSTGRES_PASSWORD: leadhub_dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - leadhub-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leadhub -d leadhub"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LeadHub API Service
  api:
    image: leadhub-service:latest
    container_name: leadhub-test-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database Configuration
      LEADHUB_DB_DSN: "postgres://leadhub:leadhub_dev_password@postgres:5432/leadhub?sslmode=disable"
      
      # Server Configuration
      PORT: 4000
      ENV: development
      
      # Rate Limiting (relaxed for testing)
      RATE_LIMIT_RPS: 10
      RATE_LIMIT_BURST: 20
      
      # SMTP Configuration (dummy for testing)
      LEADHUB_SMTP_HOST: sandbox.smtp.mailtrap.io
      LEADHUB_SMTP_USERNAME: test
      LEADHUB_SMTP_PASSWORD: test
      LEADHUB_SMTP_SENDER: "LEADHUB <no-reply@leadhub.tech>"
      
      # Database Connection Pool
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 25
      DB_MAX_IDLE_TIME: 15m
    networks:
      - leadhub-test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: leadhub-test-nginx
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/nginx.conf:ro
    networks:
      - leadhub-test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Named volumes for data persistence
volumes:
  postgres_test_data:
    driver: local

# Custom network for service communication
networks:
  leadhub-test-network:
    driver: bridge
